baseURL = 'https://tech-tom.com/'
title = "TECH-TOM"
theme = 'hugo-coder'
languageCode = 'en'
defaultContentLanguage = "en"
paginate = 20
enableEmoji = true

[params]
    author = "Tom de Leeuw"
    description = "Tom's Tech Blog"
    keywords = "blog,developer,personal"
    info = ["Automation Proletarian"]
    dateFormat = "January 2, 2006"
    since = 2022
    colorScheme = "dark"
    avatarURL = "https://avatars.githubusercontent.com/u/36704245?s=400&u=443838ef61f16d65cb2933fb69ca9a68abf2b687&v=4"
    #customSCSS = ["css/custom.scss"]
    customCSS = ["css/custom.css"]

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"

[[params.social]]
  name = "Github"
  icon = "fa fa-2x fa-github"
  weight = 1
  url = "https://github.com/tomskovich/"

[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-2x fa-linkedin"
  weight = 4
  url = "https://www.linkedin.com/in/tom-de-leeuw-32a971104/"

[languages.en]
  languageName = ":uk:"

[[languages.en.menu.main]]
  name = "Blog"
  weight = 1
  url = "posts/"

[[languages.en.menu.main]]
  name = "Projects"
  weight = 2
  url = "projects/"

[[languages.en.menu.main]]
  name = "Contact"
  weight = 3
  url = "contact/"