baseURL = 'https://tech-tom.com/'
title = "TECH-TOM.com"
theme = 'PaperMod'
languageCode = 'en'
defaultContentLanguage = "en"
paginate = 20
enableEmoji = true
pygmentsCodeFences=true
googleAnalytics = 'UA-238022325-1'

[params]
env = "production"
author = "TOM DE LEEUW"
description = "Tom's Tech Blog"
keywords = ["blog,developer,personal"]
info = ["Automation Warrior"]
dateFormat = "January 2, 2006"
since = 2022
defaultTheme = "dark"
ShowReadingTime = false
ShowWordCount = false
ShowBreadCrumbs = true
ShowPostNavLinks = false
ShowCodeCopyButtons = true
showtoc = false
UseHugoToc = false

[params.homeInfoParams]
Title = "TECH-TOM"
Content = "Automation Warrior"

[[params.socialIcons]]
name = "GitHub"
url = "https://github.com/tomskovich/"

[[params.socialIcons]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/tom-de-leeuw-32a971104/"

[params.assets]
favicon = "favicon.ico"
favicon16x16 = "favicon-16x16.png"
favicon32x32 = "favicon-32x32.png"
apple_touch_icon = "apple-touch-icon.png"

[params.profileMode]
enabled = false
title = "TECH-TOM"
subtitle = "Automation Warrior"
imageUrl = "avatar.png"
imageWidth = 120
imageHeight = 120
imageTitle = "TECH-TOM"

[params.googleTagManager]
    id = "G-T00DJJN637"

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    noHl = false
    style = 'native'
    tabWidth = 4

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"

[[params.social]]
  name = "Github"
  icon = "fa fa-2x fa-github"
  weight = 1
  url = "https://github.com/tomskovich/"

[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-2x fa-linkedin"
  weight = 4
  url = "https://www.linkedin.com/in/tom-de-leeuw-32a971104/"

[languages.en]
  languageName = ":uk:"

[[languages.en.menu.main]]
  name = "Posts"
  weight = 1
  url = "posts/"

[[languages.en.menu.main]]
  name = "Tags"
  weight = 1
  url = "tags/"

[[languages.en.menu.main]]
  name = "Contact"
  weight = 2
  url = "contact/"

[[languages.en.menu.main]]
  name = "Search"
  weight = 3
  url = "search/"